### ISSUE TITLE
Support Dart SDK >= 2.0.0

### ISSUE THREAD

**Issue by mik01aj** [sass/linter#18]
I tried running the linter, but it fails on my machine:
```
~/github/linter/$ pub get
Resolving dependencies... 
The current Dart SDK version is 2.1.0.
Because sass_linter requires SDK version >=1.22.0 <2.0.0, version solving failed.
```
I wonder, maybe this needs just a config change in [`pubspec.yaml`](https://github.com/sass/linter/blob/master/pubspec.yaml)?

(FWIW, I tried this, and then it says: `Because sass_linter depends on test >=0.12.0-beta.3 <1.3.0 which requires SDK version >=1.8.0  <2.0.0-∞, version solving failed.` - so it looks like there's more work to be done.)

**Comment by srawlins** [comment]
Hi @mik01aj , you're exactly right. Both `test` and the SDK's versions should be bumped in `pubspec.yaml`.
